wallpaper {
    monitor = DP-1
    path = /home/dyna/.config/ml4w/wallpapers/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/dyna/.config/ml4w/wallpapers/wallpaper.png
    fit_mode = cover
}

splash = false

