wallpaper {
    monitor = DP-1
    path = /home/dyna/backgrounds/main.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/dyna/backgrounds/main.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/dyna/backgrounds/main.png
    fit_mode = cover
}

splash = false

