# DP-2 (144Hz) - left screen
monitor = DP-3, 2560x1440@240, 0x0, 1, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 1.0

# HDMI-A-2 (75Hz) - right of DP-2
monitor = HDMI-A-1, 1920x1080@144, 2560x0, 1

