# ─────────────────────────────
# Steam
# ─────────────────────────────

# Force the main Steam window to tile
windowrule = match:class ^(steam)$, tile on

# Keep small Steam windows floating
windowrule = match:class ^(steam)$, match:title ^(Friends List)$, float on
windowrule = match:class ^(steam)$, match:title ^(.*- event started.*)$, float on
windowrule = match:class ^(steam)$, match:title ^(.*- News.*)$, float on


# ─────────────────────────────
# Discord & Spotify
# ─────────────────────────────

windowrule = match:class ^(discord)$, tile on
windowrule = match:class ^(Spotify)$, tile on


# ─────────────────────────────
# Flameshot
# ─────────────────────────────

# Move window to (0,0)
windowrule = match:class flameshot, match:title flameshot, move 0 0

# Show on all workspaces
windowrule = match:class flameshot, match:title flameshot, pin on

# Tell the app it's fullscreen

# Force floating
windowrule = match:class flameshot, match:title flameshot, float on

